version: '2'

services:
  install:
      image: "node:12"
      volumes:
        - .:/tmp/repo
      working_dir: "/tmp/repo"
      command:  bash -c "npm install"
  package:
      image: "node:12"
      volumes:
        - .:/tmp/repo
      working_dir: "/tmp/repo"
      command: "npm run package"